#!/usr/bin/bash

#PBS -N deeptoolscomputeMatrix
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=8:mem=64gb
#PBS -J 1-4
#Sets current directory to working
cd ${PBS_O_WORKDIR}

module load anaconda3/personal
source activate deeptools

# SETUP FOR PBS ARRAY
# COMMENT OUT FOR SINGLE BATCH SUBMISSIONS
#####################################################################################
## Setup PBS array and assign file names stored in metadata using PBS_ARRAY_INDEX
#####################################################################################
metadata=$HOME/ThesisProject/metadata/chipseq/SRP104404/metadata_computeMatrix.csv
chip1=$(awk -F ',' -v taskID=${PBS_ARRAY_INDEX} '$1==taskID {print $2}' ${metadata})
chip2=$(awk -F ',' -v taskID=${PBS_ARRAY_INDEX} '$1==taskID {print $3}' ${metadata})

lab1=$(awk -F ',' -v taskID=${PBS_ARRAY_INDEX} '$1==taskID {print $4}' ${metadata})
lab2=$(awk -F ',' -v taskID=${PBS_ARRAY_INDEX} '$1==taskID {print $5}' ${metadata})

exp=$(awk -F ',' -v taskID=${PBS_ARRAY_INDEX} '$1==taskID {print $6}' ${metadata})
#####################################################################################

# Create inpath and outpaths
inpath=$EPHEMERAL/SRP104404/bamfiles
outpath=$HOME/data/SRP104404/bigwig

#####################################################################################
# input files
#####################################################################################
chip1=M1A_p300_1_blacklisted.bam
chip2=M1A_input3_blacklisted.bam

bam1=${inpath}/${chip1}
bam2=${inpath}/${chip2}

# creates outpath if it doesn't exist
mkdir -p ${outpath}

bamCompare -b1 ${bam1} -b2 ${bam2} --normalizeUsing RPKM -o ${outpath}/M1A_p300_log2ratio_RPKM.bw
