#!/bin/bash

#PBS -N fasterqdump_SRP104404
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=6:mem=32gb
#PBS -J 1-25

#####################################################################################
## Sets work directory to current
#####################################################################################
cd ${PBS_O_WORKDIR}


#####################################################################################
## Load sratools/3.1.0 module
#####################################################################################
module purge
module load sratoolkit/3.1.0

#####################################################################################
## SETUP FOR PBS ARRAY
## Print row/column info stored in metadata.csv based on assigned PBS_ARRAY_INDEX
#####################################################################################
metadata=$HOME/ThesisProject/metadata/atac/SraRunTable_SRP104404.csv
studyID=$(awk -F ',' -v taskID=${PBS_ARRAY_INDEX} '$1==taskID {print $2}' ${metadata})
SRR=$(awk -F ',' -v taskID=${PBS_ARRAY_INDEX} '$1==taskID {print $3}' ${metadata})

#####################################################################################
## Set input and output directories
#####################################################################################
prefix=$EPHEMERAL/${studyID}
outpath=${prefix}/fastq
tmpDir=$EPHEMERAL/tmp
ncpus=6

# Create outdir if not already present
mkdir -p ${prefix}
mkdir -p ${outpath}

#####################################################################################
## Run fasterq-dump
## -t = sets tmp directory
## -O = output directory
## -e = number of cpu cores 
#####################################################################################
fasterq-dump ${SRR} -t ${tmpDir} -O ${outpath} -e ${ncpus}
