#PBS -N macs3bdgcallpeak
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=4:mem=16gb
#PBS -J 7-8

## This script calls peaks on chipseq replicates combined with macs3 v3.0.1 cmbreps
## Input files are macs3cmb reps bedgraph scores tracks calculated using Fishers exact test

#####################################################################################
## Sets work directory to current
#####################################################################################
cd ${PBS_O_WORKDIR}

#####################################################################################
## Load macs3
#####################################################################################
module purge
module load anaconda3/personal
source activate macs3

#####################################################################################
## SETUP FOR PBS ARRAY JOB 
## Print row/column info stored in metadata.csv based on assigned PBS_ARRAY_INDEX
#####################################################################################
metadata=$HOME/ThesisProject/metadata/chipseq/SRP104404/metadata_macs3cmbreps.csv
biosample=$(awk -F ',' -v taskID=${PBS_ARRAY_INDEX} '$1==taskID {print $2}' ${metadata})

#####################################################################################
## Specify input and output directories
#####################################################################################
inpath=$EPHEMERAL/SRP104404/peaks/cmbreps
input=${inpath}/${biosample}_cmbreps.bdg
outpath=$EPHEMERAL/SRP104404/peaks/cmbreps
output=${outpath}/${biosample}_cmbreps_peaks.narrowPeak

#####################################################################################
## creates outpath if it doesn't exist
#####################################################################################
mkdir -p ${outpath}
	
#####################################################################################
## Call peaks on combined scores files with macs3 bdgpeakcall
## Scores are -log10p values. Cutoff -c set to 1.3 (p = 0.05) 
## default min frag length -l 200bp
## read length -g 50bp
#####################################################################################
macs3 bdgpeakcall -i ${input} \
	-c 1.3 \
	-l 200 \
	-g 50 \
	-o ${output}
